config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admin/sessions' }

  root to: "dashboard#index"
  resources :admins
  resources :candidates
  resources :criteria
  resources :selections
  get '/check', to: 'selections#check', as: 'check_process'
end

app/views/shareds/_breadcrumb.html.erb
<section class="content-header">
  <h1>
    <%= params[:controller].titleize %>
    <small><%= params[:action].titleize %></small>
  </h1>
  <ol class="breadcrumb">
    <li><%=link_to root_path do %>
          <i class="fa fa-dashboard"></i> Home</a>
        <% end %>
    </li>
    <li class="active"><%= params[:controller] %></li>
  </ol>
</section>

app/views/shareds/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b> 2.0
  </div>
  <strong>Copyright &copy; 2016 <a href="http://almsaeedstudio.com"></a>.Asrifidianty-For Thesis Purposes</strong> All rights reserved.
</footer>

app/views/shareds/_form_title.html.erb
<div class="col-md-12">
  <h2>
    <strong><%= params[:action].titleize %></strong>
    <small><%= controller_name.try(:singularize).try(:titleize) %></small>
  </h2>
</div>

app/views/shareds/_header.html.erb
<header class="main-header">
  <!-- Logo -->
  <%= link_to root_path, class: 'logo' do %>
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>Lab TI</b></span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>LAB TI Selection</b></span>
  <% end %>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- User Account: style can be found in dropdown.less -->
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag current_admin.avatar, class: 'user-image', alt: current_admin.email %>
            <span class="hidden-xs"><%= current_admin.email %></span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header">
              <%= image_tag current_admin.avatar, class: 'img-circle', alt: current_admin.email %>
              <p>
                <%= current_admin.email %>
                <small>Since <%= current_admin.created_at.strftime('%B %Y') %></small>
              </p>
            </li>
            <!-- Menu Body -->
            <li class="user-body">
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-right">
                <%= link_to 'Sign out', destroy_admin_session_path, method: 'delete', class: 'btn btn-default btn-flat' %>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shareds/_sidebar.html.erb
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <%= image_tag current_admin.avatar.url(:thumb), class: 'img-circle', alt: current_admin.email %>
      </div>
      <div class="pull-left info">
        <p><%= current_admin.email %></p>

        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
      <li class ="<%= active_class('dashboard')%>"> <%= link_to root_path do %>
            <i class="fa fa-dashboard"></i> <span>Dashboard</span></a>
          <% end %>
      </li>
      <li class="<%= active_class('admins')%> treeview">
        <a href="#">
          <i class="fa fa-user-secret"></i> <span>Admins</span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li class="">
            <%= link_to admins_path  do %>
              <i class="fa fa-circle-o"></i> Admin Lists </a>
            <% end %>
          </li>
        </ul>
      </li>
      <li class="header">INPUT DATA</li>
      <li class="<%= active_class('candidates')%> treeview">
        <a href="#">
          <i class="fa fa-group"></i> <span>Assistant Candidates</span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li class="">
            <%= link_to candidates_path  do %>
              <i class="fa fa-circle-o"></i> Candidates Lists </a>
            <% end %>
          </li>
          <li>
            <%= link_to new_candidate_path  do %>
              <i class="fa fa-plus-circle"></i> New Candidates </a>
            <% end %>
          </li>
        </ul>
      </li>

      <li class="<%= active_class('criteria')%> treeview">
        <a href="#">
          <i class="fa fa-list-ol"></i> <span>Criteria</span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li>
            <%= link_to criteria_path  do %>
              <i class="fa fa-circle-o"></i> Criteria Lists </a>
            <% end %>
          </li>
          <li>
            <%= link_to new_criterium_path  do %>
              <i class="fa fa-plus-circle"></i> New Criteria </a>
            <% end %>
          </li>
        </ul>
      </li>
      <li class="header">SELECTION</li>
      <li class="<%= active_class('selections')%>"> <%= link_to selections_path do %>
            <i class="fa fa-spinner text-red"></i> <span>Results</span></a>
          <% end %>
      </li>


    </ul>
  </section>
  <!-- /.sidebar -->
</aside>