config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admin/sessions' }

  root to: "dashboard#index"
  resources :admins
  resources :candidates
  resources :criteria
  resources :selections
  get '/check', to: 'selections#check', as: 'check_process'
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  def index
    @candidates = AssistantCandidate.page(params[:page]).per(params[:per_page])
    @criteria ||= Criterium.all
  end

  def new
    @candidate = AssistantCandidate.new
    @candidate.build_grades
  end

  def create
    @candidate = AssistantCandidate.new(permitted_params)
    if @candidate.save
      redirect_to candidates_path, notice: 'Success save Candidate'
    else
      @candidate.build_grades
      flash[:errors] = @candidate.errors.full_messages
      render :new
    end
  end

  def edit
    resource.build_grades
    resource
  end

  def update
    if resource.update(permitted_params)
      redirect_to candidates_path, notice: 'Success updated Candidate'
    else
      flash[:errors] = resource.errors.full_messages
      render :edit
    end
  end

  def show
    resource
  end

  def destroy
    if resource.destroy
      flash[:notice] = 'Success delete Candidate'
    else
      flash[:errors] = 'Failed to delete Candidate'
    end
    redirect_to candidates_path
  end

  private

    def resource
      @candidate ||= AssistantCandidate.find params[:id]
    end

    def permitted_params
      params.require(:assistant_candidate).permit(:name,
                                        :grade,
                                        :npm,
                                        profile_attributes:
                                          [ :gpa,
                                            :phone_number,
                                            :mobile_number,
                                            :address,
                                            :department,
                                            :faculty,
                                            :term,
                                            :class_name,
                                            :birthdate
                                           ],
                                        candidate_grades_attributes:
                                        [ :id,
                                          :grade,
                                          :criterium_id
                                        ]
                                      )
    end
end

app/views/candidates/_form.html.erb
<div class="form-group">
  <label>Name</label>
  <%= f.text_field :name, class: 'form-control', placeholder: 'FullName', required: true %>
</div>

<div class="form-group">
  <label>Student ID/ NPM</label>
  <%= f.text_field :npm, class: 'form-control', placeholder: 'Student ID/NPM', required: true %>
</div>

app/views/candidates/_grade_fields.html.erb
<div class='nested-fields col-md-6'>
  <div class="form-group">
    <label> <%=f.object.criterium.name.titleize %></label>
    <div class='col-md-12'>
      <div class='col-md-3'>
        <label>Grade/ Nilai</label>
      </div>
      <div class='col-md-6'>
        <%= f.number_field :grade, class: 'form-control', placeholder: 'Grade / Nilai' , required: true %>
        <%= f.hidden_field :criterium_id, :value => f.object.criterium_id%>
      </div>
    </div>
  </div>
</div>

app/views/candidates/_grades.html.erb
<div class="col-md-12">
  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Grade</h3>
    </div>
    <div class="box-body">
      <%= f.fields_for :candidate_grades do |grade| %>
        <%= render 'candidates/grade_fields', f: grade %>
      <% end %>
    </div>
  </div>
</div>

app/views/candidates/_profile.html.erb
<div class="col-md-12">
  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Profile Info</h3>
    </div>
      <div class="box-body">
        <div class="form-group">
          <label>GPA / IPK</label>
            <%= f.text_field :gpa, class: 'form-control', placeholder: 'GPA/IPK semester terakhir' %>
          </div>

          <div class="form-group">
            <label>Faculty/Facultas</label>
            <%= f.text_field :faculty, class: 'form-control', placeholder: 'Faculty' %>
          </div>

          <div class="form-group">
            <label>Department/Jurusan</label>
            <%= f.text_field :department, class: 'form-control', placeholder: 'Department / Jurusan' %>
          </div>

          <div class="form-group">
            <label>Term/ Semester yang dijalani</label>
            <%= f.text_field :term, class: 'form-control', placeholder: 'Semester' %>
          </div>

          <div class="form-group">
            <label>Class</label>
            <%= f.text_field :class_name, class: 'form-control', placeholder: 'Kelas saat ini' %>
          </div>

          <div class="form-group">
            <label>Home Address/ Alamat Rumah</label>
            <%= f.text_area :address, class: 'form-control', placeholder: 'Semester' %>
          </div>

          <div class="form-group">
            <label>Birth Date</label>
            <%= f.text_field :birthdate, class: 'form-control', placeholder: 'datepicker Tanggal Lahir' %>
          </div>

          <div class="form-group">
            <label>Phone Number</label>
            <%= f.number_field :phone_number, class: 'form-control', placeholder: 'Phone Number' %>
          </div>

          <div class="form-group">
            <label>Mobile Number</label>
            <%= f.number_field :mobile_number, class: 'form-control', placeholder: 'Mobile Number' %>
          </div>


      </div>
      <div class="box-footer">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
  </div>
</div>

app/views/candidates/edit.html.erb
<%= render 'shareds/breadcrumb' %>

<%= form_for @candidate, url: candidate_path(@candidate), method: 'put' do |f| %>
  <%= f.fields_for :profile do |prf| %>
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Basic Info</h3>
            </div>
            <div class="box-body">
              <%= render 'form', f: f %>
            </div>
          </div>
        </div>
        <%= render 'grades', f: f %>
        <%= render 'profile', f: prf %>
      </div>
    </section>
  <% end %>
<% end %>

app/views/candidates/index.html.erb
<%= render 'shareds/breadcrumb' %>

<section class="content">
  <div class="row">
    <div class="col-xs-12 col-md-12 col-sm-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Lists</h3>
        </div>

        <div class="box-body table-responsive">
          <table id="example2" class="table table-bordered table-hover datatable">
            <thead>
              <tr >
                <th class='text-center'>NO</th>
                <th class='text-center'>Student ID / NPM</th>
                <th class='text-center'>Name</th>
                <% @criteria.all.each do |criteria| %>
                  <th width="10%" class='text-center'><%= criteria.name.titleize %></th>
                <%end%>
                <th width="25%" class='text-center'>Action</th>
              </tr>
            </thead>
            <tbody>
              <% @candidates.each_with_index do |resource, index| %>
                <tr>
                  <td  class='text-center'><%=index+1%></td>
                  <td><%= link_to resource.npm, candidate_path(resource) %></td>
                  <td><%= resource.name %></td>
                  <% @criteria.all.each.each do |criterium|%>
                   <% criteria_grade = resource.candidate_grades.bonds.find_or_create_by('criteria.name': criterium.name).grade rescue resource.build_grade(criterium).grade %>
                    <td class = <%='zero-grade' if criteria_grade == 0%>> <%=criteria_grade%> </td>
                  <% end %>
                  <td class='text-center'>
                    <i class="fa fa-fw fa-pencil"></i>
                    <%= link_to 'Edit', edit_candidate_path(resource) %>
                    <i class="fa fa-fw fa-trash"></i>
                    <%= link_to 'Delete', candidate_path(resource), method: :delete, data:{ confirm: 'are you sure?' } %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>

        <div class="box-footer">
          <div class='text-center'>
            <%= link_to 'Process Ranking', selections_path, class: 'btn btn-warning', method: :post%>
          </div>
        </div>
        <%= paginate @candidates %>
      </div>
    </div>
  </div>
</section>

app/views/candidates/new.html.erb
<%= render 'shareds/breadcrumb' %>

<%= form_for @candidate, url: candidates_path, method: 'post' do |f| %>
  <%= f.fields_for :profile do |prf| %>
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Basic Info</h3>
            </div>
            <div class="box-body">
              <%= render 'form', f: f %>
            </div>
          </div>
        </div>
        <%= render 'grades', f: f %>
        <%= render 'profile', f: prf %>
      </div>
    </section>
  <% end %>
<% end %>

app/views/candidates/show.html.erb
<%= render 'shareds/breadcrumb' %>
<br>
<%profile = @candidate.profile%>
<div class='container'>
  <div class='col-md-9 col-md-offset-1'>
    <div class="box box-primary">
      <div class="box-body box-profile">
        <h3 class="profile-username text-center"><%= @candidate.name.titleize %></h3>

        <p class="text-muted text-center"><%= @candidate.npm.upcase %></p>
        <div class='col-md-8 col-md-offset-2'>
           <ul class="list-group">
            <li class="list-group-item">
              <b>Preference Score</b> <a class="pull-right"><%= @candidate.reference_score %></a>
            </li>
            <li class="list-group-item">
              <%Criterium.all.each do |criterium|%>
                <b><%=criterium.name%></b> <a class="pull-right"><%= CandidateGrade.find_by(assistant_candidate_id: @candidate.id, criterium_id: criterium.id).grade rescue '0'%></a><br>
              <% end%>
            </li>
          </ul>
        </div>

        <div class='col-md-8 col-md-offset-2'>
          <ul class="list-group list-group-unbordered">
            <li class="list-group-item">
              <b>Fakultas</b> <span class="pull-right"><%= profile.faculty %></span >
            </li>

            <li class="list-group-item">
              <b>Jurusan</b> <span class="pull-right"><%= profile.department %></span  >
            </li>
            <li class="list-group-item">
              <b>IPK Terakhir</b> <span class="pull-right"><%= profile.gpa %></span >
            </li>
            <li class="list-group-item">
              <b>Semester yang dijalani</b> <span class="pull-right"><%= profile.term %></span  >
            </li>
            <li class="list-group-item">
              <b>Kelas</b> <span class="pull-right"><%= profile.class_name %></span >
            </li>
            <li class="list-group-item">
              <b>Tanggal Lahir</b> <span class="pull-right"><%= profile.birthdate %></span  >
            </li>
            <li class="list-group-item">
              <b>Alamat Rumah</b> <br>
              <%= profile.address %>
            </li>
            <li class="list-group-item">
              <b>No. Handphone</b> <span class="pull-right"><%= profile.mobile_number %></span  >
            </li>
            <li class="list-group-item">
              <b>No. Telepon</b> <span class="pull-right"><%= profile.phone_number %></span >
            </li>
          </ul>
        </div>
      </div>
      <!-- /.box-body -->
    </div>
  </div>
</div>